export const USER_LOGGING_IN = 'USER_LOGGING_IN'
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'

export const PROJECT_CREATING = 'PROJECT_CREATING'
export const PROJECT_CREATED = 'PROJECT_CREATED'
export const FETCHING_PROJECTS = 'FETCHING_PROJECTS'
export const PROJECTS_FETCHED = 'PROJECTS_FETCHED'
export const SELECT_PROJECT = 'SELECT_PROJECT'

export const FETCHING_RECORDS = 'FETCHING_RECORDS'
export const RECORDS_FETCHED = 'RECORDS_FETCHED'

